root = "."
tmp_dir = "tmp"

[build]
  cmd = "make air-build"
  bin = "tmp/main"
  delay = 1000                     
  exclude_dir = ["tmp"]
  include_file = [".env"]
  include_ext = ["go", "tpl", "gohtml", "html"]
  exclude_file = [".gitignore", "README.md"]
  exclude_regex = ["_test.go"]
  pre_cmd = []                      # todo gen docs


[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[screen]
  clear_on_rebuild = false         
  keep_scroll = true

[misc]
  log = "build-errors.log"         
  clean_on_exit = false
  kill_delay = "0s"
  stop_on_error = true
